dataset: mimiciii
task: readmission_prediction
seed: 1
save_params: True
save_test: True

triplet_ratio: 6.0
code_thresh: 100  # 60 for mimiciv
visit_thresh: 15

train_batch_size: 256
val_batch_size: 256
test_batch_size: 256
max_epoch: 300
early_stopping_threshold: 20
early_stopping_indicator: AUPRC
bootstrap_num: 100
val_freq: 1
logging_freq: 50

model:
  name: Deepr
  model_type: baseline
  mode: train
  freeze: False
  args:

max_weeks_between: 630
start_embed_dim: 64
hidden_dim: 64
window_size: 2

optimizer:
  name: Adam
  args:

lr: 0.001
weight_decay: 0.

scheduler:
  name: ExpLR
  args:

gamma: 0.995

criterion:
  binary_entropy:
    reduction: mean

val_metrics:
  AUPRC:
    args: None

test_metrics:
  AUROC:
    args: None
  AUPRC:
    args: None
  F1:
    args: None

processed_data_path: ./data/processed
log_path: ./logs
pretrained:
